name: sample-laravel-modular

services:
    backend:
        build:
            context: backend
            args:
                USER_ID: ${USER_ID}
        volumes:
            - ../../backend:/app/
            - composer_cache:/home/dev/.composer

    nginx:
        build:
            context: nginx
        ports:
            - ${NGINX_PORT}:80
        volumes:
            - ../../backend/public/:/app/public/:ro
        depends_on:
            - backend

    pgsql:
        build:
            context: pgsql
        ports:
            - ${PGSQL_PORT}:5432
        env_file: pgsql/.env
        volumes:
            - pgsql:/var/lib/postgresql/data:rw
        healthcheck:
            test: /usr/bin/pg_isready
            interval: 1s
            timeout: 100s
            retries: 50
volumes:
    pgsql:
    composer_cache:
